apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        apps: webapp
    spec:
      containers:
        name: webapp
        image: bijan588/a4_v2-web:latest
        ports: 
        env:
          - name: REDIS-HOST
            value: redis-service